/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {PageTeaserProps} from "../page-teaser/PageTeaserProps";

/**
 * Offset of the signpost to overlap the previous section
 */
export type Offset = boolean;
export type Label = string;
export type Icon = string;
export type Tabs = {
  label?: Label;
  icon?: Icon;
  /**
   * Referenced component PageTeaserProps
   */
  pageTeaser?: PageTeaserProps;
}[];
/**
 * Add additional css classes that should be applied to the logo
 */
export type AdditionalClasses = string;

export interface SignpostProps {
  offset?: Offset;
  tabs?: Tabs;
  className?: AdditionalClasses;
}
