/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Copy text for the element
 */
export type TextContent = string;
/**
 * Visually highlight the text
 */
export type HighlightText = boolean;
/**
 * URL of the image to display
 */
export type ImageSource = string;
/**
 * Alt text of the image
 */
export type AltText = string;
/**
 * In relation to the text content
 */
export type MediaAlignment =
  | "above-left"
  | "above-center"
  | "above-right"
  | "beside-left"
  | "beside-right"
  | "intext-left"
  | "intext-right"
  | "below-left"
  | "below-center"
  | "below-right";

/**
 * Component used to display an image beside or above/below a text block
 */
export interface ImageTextProps {
  text: TextContent;
  highlightText?: HighlightText;
  image: {
    src?: ImageSource;
    alt?: AltText;
  };
  layout: MediaAlignment;
}
