/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {ButtonProps} from "../button/ButtonProps";

/**
 * Headline for the module element
 */
export type ModuleHeadline = string;
/**
 * Make the headline larger
 */
export type LargeHeadline = boolean;
/**
 * Subheadline below the module headline
 */
export type ModuleSubheadline = string;
/**
 * Info text for the module element
 */
export type ModuleText = string;
/**
 * Choose the layout for the component
 */
export type Layout = "textLeft" | "imageLeft";
/**
 * Give the component padding
 */
export type Padding = boolean;
/**
 * Buttons of the Button Group
 */
export type Buttons = ButtonProps[];
/**
 * Image source to use
 */
export type ImageSource = string;
/**
 * The aspect ratio of the image
 */
export type AspectRatio = "unset" | "square" | "wide" | "landscape";
/**
 * Image description
 */
export type AltText = string;
/**
 * Select a vertical alignment for the image
 */
export type ImageVerticalAlignment = "center" | "top" | "bottom";
/**
 * Choose the alginment of the text
 */
export type TextAlignment = "left" | "center";

export interface ImageStoryProps {
  headline?: ModuleHeadline;
  largeHeadline?: LargeHeadline;
  sub?: ModuleSubheadline;
  text?: ModuleText;
  layout?: Layout;
  padding?: Padding;
  buttons?: Buttons;
  image?: Image;
  textAlign?: TextAlignment;
}
/**
 * Image displayed alongside the text content
 */
export interface Image {
  src?: ImageSource;
  aspectRatio?: AspectRatio;
  alt?: AltText;
  vAlign?: ImageVerticalAlignment;
}
