/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ImageSource = string;
export type ImageAltText = string;
/**
 * Choose what widget to display in the teaser
 */
export type Widget = "image" | "energyCalculator" | "timetable";
export type Label = string;
export type URL = string;
/**
 * A list of links to display in the teaser
 */
export type Links = {
  label: Label;
  target: URL;
}[];
/**
 * Add additional css classes that should be applied to the logo
 */
export type AdditionalClasses = string;

export interface PageTeaserProps {
  image?: Image;
  widget?: Widget;
  links?: Links;
  className?: AdditionalClasses;
}
/**
 * The image to display in the teaser
 */
export interface Image {
  src: ImageSource;
  alt?: ImageAltText;
}
