/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Picture source
 */
export type Source = string;
/**
 * Picture source
 */
export type Source1 = string;
/**
 * Toggle wether the inverted or default version of the logo is being displayed
 */
export type Inverted = boolean;
/**
 * Alt text to display for picture
 */
export type AltText = string;
/**
 * Width of the picture
 */
export type Width = number;
/**
 * Height of the picture
 */
export type Height = number;

export interface LogoProps {
  src?: Source;
  srcInverted?: Source1;
  inverted?: Inverted;
  alt?: AltText;
  width?: Width;
  height?: Height;
  homepageHref?: string;
}
