/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Name of the contact
 */
export type Label = string;

/**
 * Component used for user interaction
 */
export interface ContactProps {
  name?: Label;
}
