/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Topic for the content nav card
 */
export type Topic = string;
/**
 * Label for the Content Nav Card
 */
export type Label = string;
/**
 * URL of the image to display
 */
export type ImageSource = string;
/**
 * Alternative text for the image
 */
export type AltText = string;
/**
 * Whether the card should feature a campaign green banderole at the bottom of the image
 */
export type CampaignGreen = boolean;
/**
 * Label of the button. Still A11Y relevant when the button is hidden.
 */
export type Label1 = string;
/**
 * URL to navigate to when the button is clicked
 */
export type Target = string;
/**
 * Label of the button. Still A11Y relevant when the button is hidden.
 */
export type Label2 = string;
/**
 * URL to navigate to when the button is clicked
 */
export type LinkURL = string;

/**
 * Component used to tease content
 */
export interface ContentNavCardProps {
  topic: Topic;
  label?: Label;
  image: Image;
  campaignGreen?: CampaignGreen;
  link: Link;
  secondaryLink?: {
    label: Label2;
    target?: LinkURL;
  };
}
/**
 * Image to display as cover
 */
export interface Image {
  src?: ImageSource;
  alt?: AltText;
}
/**
 * Link to navigate to when the button or the image is clicked
 */
export interface Link {
  label: Label1;
  target?: Target;
}
