/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {LogoProps} from "../logo/LogoProps";

/**
 * Small line of text displayed below the logo
 */
export type Byline = string;
/**
 * Invert the color scheme of the footer
 */
export type Inverted = boolean;

export interface FooterProps {
  /**
   * Referenced component LogoProps
   */
  logo: LogoProps;
  byline?: Byline;
  inverted?: Inverted;
  navItems?: {
    href: string;
    label: string;
    active?: boolean;
  }[];
}
