/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The testimonial layout
 */
export type Layout = "slider" | "list" | "alternating";
/**
 * The style of the quote signs
 */
export type StyleOfTheQuoteSigns = "normal" | "large" | "none";
/**
 * The testimonial quote
 */
export type Quote = string;
/**
 * The name of the quote author
 */
export type Name = string;
/**
 * The title of the quote author
 */
export type Title = string;
/**
 * The image to display with the testimonial
 */
export type Source = string;
/**
 * The alt text of the image file
 */
export type AltText = string;
/**
 * The rating of the testimonial, from 1 to 5
 */
export type Rating = number;
/**
 * Add testimonials featuring an image, a quote, a source and a rating
 */
export type Testimonials = Testimonial[];

/**
 * Display testimonials with an optional image and rating
 */
export interface TestimonialsProps {
  layout?: Layout;
  quoteSigns?: StyleOfTheQuoteSigns;
  testimonial?: Testimonials;
}
/**
 * Testimonial entry of Testimonials component
 */
export interface Testimonial {
  quote: Quote;
  name: Name;
  title?: Title;
  image: {
    src?: Source;
    alt?: AltText;
  };
  rating?: Rating;
}
