/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import type {StatProps} from "../stat/StatProps";

/**
 * The stats to display with a number upcounter
 *
 * @minItems 1
 * @maxItems 4
 */
export type Stats =
  | [StatProps]
  | [StatProps, StatProps]
  | [StatProps, StatProps, StatProps]
  | [StatProps, StatProps, StatProps, StatProps];

/**
 * Component used to display stats with a number upcounter
 */
export interface StatsProps {
  stat?: Stats;
}
